# -*- coding: utf-8 -*-
"""E7 2/2 (sizinti): parcasiz cozumun uc tur cevabini dosyalara yazar.

Cevaplar model tarafindan dogrulama/metinsiz-secim.json uzerinden verildi
(pasaj klasoru hic acilmadi, orijinal soru dosyalari okunmadi). Uc tur ayni
oturumda cozuldugu icin tam bagimsiz degildir; kararsiz kalinan sorularda
turlar bilerek farkli cevaplar tasir. Ayrintili serhler METINSIZ-RAPOR-2.md'de.

Cikti: kalibrasyon/metinsiz/yeniden-olcum-tur{1,2,3}.json
"""
import json
import os

# id: ([tur1, tur2, tur3], basis)
C = {
    # ---- practice / matching-features
    "practice-matching-features-1": (["C", "C", "C"], "general_knowledge"),
    "practice-matching-features-5": (["B", "B", "B"], "logic"),
    "practice-matching-features-9": (["E", "E", "E"], "logic"),
    "practice-matching-features-10": (["A", "E", "A"], "guess"),
    # ---- practice / matching-headings
    "practice-matching-headings-11": (["i", "vii", "i"], "logic"),
    "practice-matching-headings-14": (["ix", "ix", "v"], "logic"),
    "practice-matching-headings-15": (["v", "ii", "v"], "logic"),
    # ---- practice / matching-information
    "practice-matching-information-6": (["H", "G", "F"], "guess"),
    # ---- practice / matching-sentence-endings
    "practice-matching-sentence-endings-1": (["A", "A", "A"], "logic"),
    "practice-matching-sentence-endings-2": (["E", "E", "E"], "logic"),
    "practice-matching-sentence-endings-3": (["B", "B", "B"], "logic"),
    "practice-matching-sentence-endings-4": (["C", "C", "C"], "logic"),
    "practice-matching-sentence-endings-5": (["D", "D", "D"], "logic"),
    "practice-matching-sentence-endings-6": (["B", "B", "B"], "option_wording"),
    "practice-matching-sentence-endings-7": (["G", "C", "G"], "logic"),
    "practice-matching-sentence-endings-8": (["D", "D", "D"], "logic"),
    "practice-matching-sentence-endings-9": (["A", "A", "A"], "logic"),
    "practice-matching-sentence-endings-10": (["E", "E", "E"], "logic"),
    # ---- practice / multiple-choice
    "practice-multiple-choice-1": (["B", "D", "B"], "guess"),
    "practice-multiple-choice-2": (["A", "A", "A"], "logic"),
    "practice-multiple-choice-3-4": ([["C", "F"], ["C", "F"], ["C", "F"]], "general_knowledge"),
    "practice-multiple-choice-5": (["B", "B", "B"], "general_knowledge"),
    "practice-multiple-choice-6": (["B", "D", "B"], "guess"),
    "practice-multiple-choice-7-8": ([["C", "F"], ["C", "F"], ["C", "F"]], "logic"),
    "practice-multiple-choice-9-10": ([["D", "E"], ["D", "E"], ["D", "E"]], "logic"),
    "practice-multiple-choice-11": (["B", "B", "B"], "logic"),
    "practice-multiple-choice-12": (["C", "C", "C"], "general_knowledge"),
    "practice-multiple-choice-13": (["A", "C", "A"], "guess"),
    "practice-multiple-choice-14": (["C", "A", "C"], "logic"),
    "practice-multiple-choice-15": (["D", "D", "D"], "logic"),
    # ---- practice / note-completion
    "practice-note-completion-1": (["1,200", "3,600", "2,000"], "guess"),
    "practice-note-completion-10": (["500", "800", "550"], "guess"),
    # ---- practice / sentence-completion
    "practice-sentence-completion-1": (["cube", "cube", "cube"], "logic"),
    "practice-sentence-completion-3": (["straight", "some distance", "straight"], "guess"),
    "practice-sentence-completion-8": (["preview", "time machine", "preview"], "guess"),
    "practice-sentence-completion-10": (["six hours", "ten hours", "six hours"], "guess"),
    "practice-sentence-completion-11": (["S/2025 U1", "S/2025 U1", "S/2025 U1"], "general_knowledge"),
    "practice-sentence-completion-12": (["56,000 kilometres", "56,000 kilometres", "56,000 kilometres"], "general_knowledge"),
    # ---- practice / short-answer
    "practice-short-answer-4": (["ten", "ten", "ten"], "general_knowledge"),
    "practice-short-answer-6": (["30", "12", "25"], "guess"),
    "practice-short-answer-8": (["26 November", "24 November", "26 November"], "logic"),
    # ---- practice / summary-completion
    "practice-summary-completion-1": (["7", "5", "13"], "guess"),
    "practice-summary-completion-2": (["15", "18", "15"], "guess"),
    "practice-summary-completion-4": (["professionals", "teams", "professionals"], "logic"),
    "practice-summary-completion-6": (["crossover", "crossover", "crossover"], "general_knowledge"),
    "practice-summary-completion-9": (["110", "120", "108"], "guess"),
    "practice-summary-completion-10": (["diary", "diary", "diary"], "logic"),
    "practice-summary-completion-12": (["twice", "twice", "twice"], "general_knowledge"),
    # ---- practice / true-false-not-given
    "practice-true-false-not-given-3": (["TRUE", "NOT GIVEN", "TRUE"], "general_knowledge"),
    "practice-true-false-not-given-4": (["FALSE", "FALSE", "NOT GIVEN"], "general_knowledge"),
    "practice-true-false-not-given-7": (["TRUE", "TRUE", "NOT GIVEN"], "logic"),
    "practice-true-false-not-given-8": (["FALSE", "NOT GIVEN", "FALSE"], "logic"),
    "practice-true-false-not-given-10": (["NOT GIVEN", "NOT GIVEN", "FALSE"], "guess"),
    "practice-true-false-not-given-11": (["FALSE", "FALSE", "FALSE"], "general_knowledge"),
    "practice-true-false-not-given-13": (["NOT GIVEN", "FALSE", "NOT GIVEN"], "general_knowledge"),
    "practice-true-false-not-given-15": (["TRUE", "NOT GIVEN", "TRUE"], "general_knowledge"),
    # ---- practice / yes-no-not-given
    "practice-yes-no-not-given-1": (["NOT GIVEN", "YES", "NOT GIVEN"], "logic"),
    "practice-yes-no-not-given-2": (["YES", "YES", "YES"], "logic"),
    "practice-yes-no-not-given-3": (["NO", "NO", "NO"], "logic"),
    "practice-yes-no-not-given-4": (["NOT GIVEN", "NO", "NOT GIVEN"], "guess"),
    "practice-yes-no-not-given-5": (["YES", "YES", "NOT GIVEN"], "logic"),
    "practice-yes-no-not-given-6": (["NO", "NO", "NO"], "logic"),
    "practice-yes-no-not-given-7": (["YES", "YES", "YES"], "logic"),
    "practice-yes-no-not-given-8": (["NOT GIVEN", "NO", "NOT GIVEN"], "logic"),
    "practice-yes-no-not-given-9": (["NO", "NO", "NO"], "logic"),
    "practice-yes-no-not-given-10": (["NOT GIVEN", "YES", "NOT GIVEN"], "logic"),
    "practice-yes-no-not-given-11": (["YES", "NOT GIVEN", "YES"], "guess"),
    "practice-yes-no-not-given-12": (["YES", "YES", "NOT GIVEN"], "general_knowledge"),
    "practice-yes-no-not-given-13": (["YES", "YES", "NOT GIVEN"], "logic"),
    "practice-yes-no-not-given-14": (["NO", "NOT GIVEN", "NO"], "logic"),
    "practice-yes-no-not-given-15": (["NOT GIVEN", "NOT GIVEN", "NO"], "guess"),
    # ---- AC1
    "AC1-matching-features-23": (["E", "E", "B"], "logic"),
    "AC1-matching-features-25": (["C", "C", "D"], "logic"),
    "AC1-matching-features-26": (["A", "A", "B"], "logic"),
    "AC1-multiple-choice-32": (["D", "D", "D"], "general_knowledge"),
    "AC1-multiple-choice-33": (["B", "A", "B"], "guess"),
    "AC1-multiple-choice-34-35": ([["A", "E"], ["A", "E"], ["A", "E"]], "logic"),
    "AC1-note-completion-4": (["ball", "ball", "tyre"], "general_knowledge"),
    "AC1-note-completion-5": (["gate", "screen", "gate"], "guess"),
    "AC1-sentence-completion-19": (["clear screen", "see-through screen", "clear screen"], "logic"),
    "AC1-sentence-completion-20": (["hierarchy", "dominance hierarchy", "hierarchy"], "logic"),
    "AC1-sentence-completion-22": (["fifteen minutes", "fifteen minutes", "fifteen minutes"], "logic"),
    "AC1-summary-completion-36": (["rim", "rim", "rim"], "option_wording"),
    "AC1-summary-completion-38": (["algae", "algal mats", "algae"], "general_knowledge"),
    "AC1-summary-completion-39": (["Nature", "Science Advances", "Nature Climate Change"], "guess"),
    "AC1-summary-completion-40": (["natural laboratory", "preview", "crystal ball"], "guess"),
    "AC1-true-false-not-given-7": (["FALSE", "FALSE", "NOT GIVEN"], "general_knowledge"),
    "AC1-true-false-not-given-9": (["FALSE", "NOT GIVEN", "FALSE"], "logic"),
    "AC1-true-false-not-given-10": (["FALSE", "FALSE", "FALSE"], "option_wording"),
    "AC1-true-false-not-given-11": (["TRUE", "TRUE", "TRUE"], "logic"),
    "AC1-true-false-not-given-12": (["FALSE", "FALSE", "FALSE"], "general_knowledge"),
    "AC1-true-false-not-given-13": (["NOT GIVEN", "NOT GIVEN", "FALSE"], "guess"),
    # ---- AC2
    "AC2-flow-chart-completion-1": (["40 minutes", "40 minutes", "40 minutes"], "general_knowledge"),
    "AC2-flow-chart-completion-2": (["August 2025", "February 2025", "August 2025"], "general_knowledge"),
    "AC2-flow-chart-completion-3": (["ten kilometres", "ten kilometres", "ten kilometres"], "general_knowledge"),
    "AC2-flow-chart-completion-6": (["Voyager 2", "Voyager 2 flyby", "Voyager 2"], "general_knowledge"),
    "AC2-matching-features-23": (["D", "D", "D"], "option_wording"),
    "AC2-matching-features-24": (["E", "E", "E"], "logic"),
    "AC2-matching-features-25": (["C", "B", "C"], "guess"),
    "AC2-matching-features-26": (["A", "A", "A"], "logic"),
    "AC2-matching-headings-14": (["iv", "iv", "ix"], "logic"),
    "AC2-multiple-choice-32": (["B", "B", "B"], "logic"),
    "AC2-multiple-choice-33": (["D", "D", "D"], "logic"),
    "AC2-multiple-choice-34-35": ([["C", "D"], ["C", "F"], ["C", "D"]], "logic"),
    "AC2-sentence-completion-21": (["197", "220", "197"], "guess"),
    "AC2-sentence-completion-22": (["eight", "five", "eight"], "guess"),
    "AC2-summary-completion-36": (["D", "D", "D"], "general_knowledge"),
    "AC2-summary-completion-37": (["E", "C", "E"], "logic"),
    "AC2-summary-completion-38": (["I", "I", "I"], "logic"),
    "AC2-summary-completion-39": (["H", "H", "H"], "logic"),
    "AC2-summary-completion-40": (["B", "B", "J"], "logic"),
    "AC2-true-false-not-given-10": (["NOT GIVEN", "FALSE", "NOT GIVEN"], "logic"),
    "AC2-true-false-not-given-11": (["TRUE", "TRUE", "TRUE"], "logic"),
    "AC2-true-false-not-given-12": (["FALSE", "FALSE", "FALSE"], "option_wording"),
    "AC2-true-false-not-given-13": (["NOT GIVEN", "FALSE", "NOT GIVEN"], "logic"),
    # ---- AC3
    "AC3-matching-features-23": (["D", "D", "D"], "option_wording"),
    "AC3-matching-features-24": (["B", "C", "B"], "logic"),
    "AC3-matching-features-25": (["C", "B", "C"], "logic"),
    "AC3-matching-features-26": (["A", "A", "A"], "logic"),
    "AC3-matching-headings-14": (["ii", "ii", "ii"], "logic"),
    "AC3-matching-information-28": (["G", "B", "H"], "guess"),
    "AC3-multiple-choice-32": (["D", "B", "D"], "guess"),
    "AC3-multiple-choice-33": (["C", "C", "C"], "logic"),
    "AC3-multiple-choice-34-35": ([["B", "F"], ["B", "F"], ["B", "F"]], "logic"),
    "AC3-sentence-completion-19": (["west", "north", "west"], "guess"),
    "AC3-sentence-completion-20": (["bright", "bright", "bright"], "general_knowledge"),
    "AC3-sentence-completion-21": (["two", "three", "two"], "guess"),
    "AC3-sentence-completion-22": (["analysts", "analysts", "analysts"], "logic"),
    "AC3-summary-completion-38": (["dendritic spines", "synapses", "spines"], "general_knowledge"),
    "AC3-summary-completion-40": (["temperatures", "temperatures", "temperatures"], "logic"),
    "AC3-table-completion-6": (["left eye", "preferred eye", "left eye"], "general_knowledge"),
    "AC3-true-false-not-given-7": (["TRUE", "TRUE", "NOT GIVEN"], "general_knowledge"),
    # ---- AC4
    "AC4-matching-features-24": (["D", "C", "D"], "general_knowledge"),
    "AC4-matching-features-25": (["D", "A", "D"], "guess"),
    "AC4-matching-features-26": (["B", "B", "B"], "general_knowledge"),
    "AC4-matching-headings-17": (["viii", "viii", "viii"], "logic"),
    "AC4-matching-headings-18": (["iv", "iv", "iv"], "logic"),
    "AC4-multiple-choice-32": (["C", "C", "A"], "logic"),
    "AC4-multiple-choice-33": (["D", "A", "D"], "guess"),
    "AC4-multiple-choice-34-35": ([["C", "D"], ["C", "D"], ["C", "F"]], "logic"),
    "AC4-note-completion-4": (["stress", "mood", "stress"], "guess"),
    "AC4-sentence-completion-20": (["two minutes", "a minute", "two minutes"], "guess"),
    "AC4-sentence-completion-21": (["65-item", "sixty-five-item", "65-item"], "general_knowledge"),
    "AC4-sentence-completion-22": (["23", "24", "23"], "guess"),
    "AC4-summary-completion-36": (["J", "I", "J"], "guess"),
    "AC4-summary-completion-37": (["B", "B", "B"], "logic"),
    "AC4-summary-completion-38": (["D", "D", "D"], "option_wording"),
    "AC4-summary-completion-39": (["F", "F", "F"], "logic"),
    "AC4-summary-completion-40": (["A", "A", "A"], "logic"),
    "AC4-true-false-not-given-7": (["NOT GIVEN", "NOT GIVEN", "FALSE"], "guess"),
    "AC4-true-false-not-given-13": (["TRUE", "NOT GIVEN", "TRUE"], "guess"),
    # ---- GT1
    "GT1-matching-headings-31": (["viii", "viii", "viii"], "logic"),
    "GT1-multiple-choice-21": (["A", "A", "A"], "general_knowledge"),
    "GT1-multiple-choice-22": (["B", "B", "B"], "option_wording"),
    "GT1-multiple-choice-23-24": ([["C", "G"], ["C", "G"], ["C", "G"]], "general_knowledge"),
    "GT1-note-completion-15": (["noticeboard", "noticeboard", "intranet"], "general_knowledge"),
    "GT1-note-completion-16": (["staggered", "staggered", "staggered"], "logic"),
    "GT1-note-completion-19": (["eleven hours", "eleven hours", "eleven hours"], "general_knowledge"),
    "GT1-sentence-completion-26": (["40-hour", "39-hour", "40-hour"], "guess"),
    "GT1-sentence-completion-27": (["ten hours", "eight hours", "ten hours"], "guess"),
    "GT1-summary-completion-37": (["peel", "skins", "peel"], "general_knowledge"),
    "GT1-summary-completion-40": (["reduction", "prevention", "reduction"], "logic"),
    "GT1-true-false-not-given-8": (["TRUE", "TRUE", "NOT GIVEN"], "general_knowledge"),
    "GT1-true-false-not-given-9": (["TRUE", "NOT GIVEN", "TRUE"], "guess"),
    "GT1-true-false-not-given-10": (["FALSE", "NOT GIVEN", "NOT GIVEN"], "guess"),
    "GT1-true-false-not-given-12": (["FALSE", "FALSE", "FALSE"], "general_knowledge"),
    "GT1-yes-no-not-given-33": (["YES", "YES", "YES"], "logic"),
    "GT1-yes-no-not-given-34": (["YES", "NOT GIVEN", "YES"], "logic"),
    "GT1-yes-no-not-given-35": (["YES", "YES", "YES"], "logic"),
    "GT1-yes-no-not-given-36": (["NOT GIVEN", "YES", "NOT GIVEN"], "logic"),
    # ---- GT2
    "GT2-multiple-choice-21": (["C", "A", "C"], "logic"),
    "GT2-multiple-choice-22": (["A", "A", "A"], "general_knowledge"),
    "GT2-multiple-choice-23-24": ([["B", "G"], ["E", "F"], ["B", "G"]], "logic"),
    "GT2-sentence-completion-25": (["10 Mbps", "25 Mbps", "10 Mbps"], "guess"),
    "GT2-summary-completion-37": (["B", "B", "B"], "logic"),
    "GT2-summary-completion-38": (["G", "G", "G"], "logic"),
    "GT2-summary-completion-39": (["I", "I", "I"], "logic"),
    "GT2-summary-completion-40": (["A", "A", "A"], "logic"),
    "GT2-table-completion-16": (["500-word", "personal", "500-word"], "guess"),
    "GT2-table-completion-20": (["halfway", "halfway", "halfway"], "logic"),
    "GT2-true-false-not-given-9": (["FALSE", "FALSE", "NOT GIVEN"], "general_knowledge"),
    "GT2-true-false-not-given-10": (["NOT GIVEN", "TRUE", "NOT GIVEN"], "guess"),
    "GT2-true-false-not-given-11": (["TRUE", "NOT GIVEN", "TRUE"], "general_knowledge"),
    "GT2-true-false-not-given-13": (["NOT GIVEN", "NOT GIVEN", "TRUE"], "guess"),
    "GT2-true-false-not-given-14": (["NOT GIVEN", "TRUE", "NOT GIVEN"], "guess"),
    "GT2-yes-no-not-given-33": (["NOT GIVEN", "YES", "NOT GIVEN"], "logic"),
    "GT2-yes-no-not-given-34": (["NOT GIVEN", "YES", "NOT GIVEN"], "guess"),
    "GT2-yes-no-not-given-35": (["YES", "YES", "YES"], "logic"),
    "GT2-yes-no-not-given-36": (["NO", "NO", "NO"], "logic"),
}

os.makedirs(os.path.join("kalibrasyon", "metinsiz"), exist_ok=True)
for tur in (1, 2, 3):
    answers = []
    for sid, (cevaplar, basis) in C.items():
        answers.append({"id": sid, "answer": cevaplar[tur - 1], "basis": basis})
    yol = os.path.join("kalibrasyon", "metinsiz", "yeniden-olcum-tur%d.json" % tur)
    with open(yol, "w", encoding="utf-8") as f:
        json.dump({"answers": answers}, f, ensure_ascii=False, indent=1)
    print("yazildi:", yol, "(%d cevap)" % len(answers))
